version: 2.1

orbs:
  cypress: cypress-io/cypress@1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: yarn install
  test: 
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: yarn test

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build