version: 2.1

orbs:
  cypress: cypress-io/cypress@1

jobs:
  build_and_unit_test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: run jest tests
          command: yarn test
      - run:
          name: bundle files
          command: yarn build
  deploy: 
    docker:
      - image: circleci/node:14
    steps: 
      - attach_workspace:
          at: ./
      - run: 
          name: deploy to netlify
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --dir=dist --prod
workflows:
  build_test_deploy:
    jobs:
      - build_and_unit_test
      - cypress/run:
          executor: with-chrome
          browser: chrome
          yarn: true
          start: yarn start
          requires:
            - build_and_unit_test
      - deploy:
          requires:
            - build_and_unit_test
            - cypress/run
          filters:
             branches:
               only: main