version: 2.1

orbs:
  cypress: cypress-io/cypress@1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: run jest tests
          command: yarn test

workflows:
  build_and_test:
    jobs:
      - build
      - cypress/run:
          store_artifacts: true
          yarn: true
          start: yarn start
          requires:
            - build
          filters:
             branches:
               only: main